idf_component_register(SRCS
                        "main.cpp"
                        "link_protocol.cpp"
                        "mode_manager.cpp"
                        "IMyGamepad.cpp"
                        "XboxOneGamepad.cpp"
                        "SwitchProController.cpp"
                        "DualSenseController.cpp"
                    INCLUDE_DIRS ".")
